language: node_js
node_js:
  - "5"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install :
  - npm install -g gulp
  - gem install sass scss_lint_reporter_checkstyle

cache:
  directories:
    - node_modules

script:
  - gulp dev
  - gulp prod

after_success: "bash scripts/build_n_push.sh"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e274ad601caf28d0f0ee
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
