/** @format */

// flow-typed signature: ff01eb5d9f253e9eebb76e21e16d4d7e
// flow-typed version: <<STUB>>/cjs_v^0.0.11/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "cjs" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "cjs/cjs" {
  declare module.exports: any;
}

// Filename aliases
declare module "cjs/cjs.js" {
  declare module.exports: $Exports<"cjs/cjs">;
}
