// flow-typed signature: 2eddd2a744f308b746e1a45b22a593a1
// flow-typed version: <<STUB>>/css-module-flow_v1.0.0/flow_v0.95.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-module-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-module-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'css-module-flow/index' {
  declare module.exports: $Exports<'css-module-flow'>;
}
declare module 'css-module-flow/index.js' {
  declare module.exports: $Exports<'css-module-flow'>;
}
