// flow-typed signature: b1e8a71bf6fe6778b36317d9c3ff44a6
// flow-typed version: <<STUB>>/css-minimizer-webpack-plugin_v3.4.1/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-minimizer-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-minimizer-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-minimizer-webpack-plugin/dist' {
  declare module.exports: any;
}

declare module 'css-minimizer-webpack-plugin/dist/minify' {
  declare module.exports: any;
}

declare module 'css-minimizer-webpack-plugin/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-minimizer-webpack-plugin/dist/index' {
  declare module.exports: $Exports<'css-minimizer-webpack-plugin/dist'>;
}
declare module 'css-minimizer-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'css-minimizer-webpack-plugin/dist'>;
}
declare module 'css-minimizer-webpack-plugin/dist/minify.js' {
  declare module.exports: $Exports<'css-minimizer-webpack-plugin/dist/minify'>;
}
declare module 'css-minimizer-webpack-plugin/dist/utils.js' {
  declare module.exports: $Exports<'css-minimizer-webpack-plugin/dist/utils'>;
}
