// flow-typed signature: ba838d72c62315a9cc98246ca15275d9
// flow-typed version: <<STUB>>/cssnano_v4.1.7/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cssnano'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cssnano' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cssnano/dist/index' {
  declare module.exports: any;
}

declare module 'cssnano/quickstart' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cssnano/dist/index.js' {
  declare module.exports: $Exports<'cssnano/dist/index'>;
}
declare module 'cssnano/quickstart.js' {
  declare module.exports: $Exports<'cssnano/quickstart'>;
}
