/** @format */

// flow-typed signature: 0adf5ddf6282df91b2b5950729d614c0
// flow-typed version: <<STUB>>/imagemin-webpack-plugin_v^2.1.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imagemin-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "imagemin-webpack-plugin" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "imagemin-webpack-plugin/dist/helpers" {
  declare module.exports: any;
}

declare module "imagemin-webpack-plugin/dist/index" {
  declare module.exports: any;
}

declare module "imagemin-webpack-plugin/src/helpers" {
  declare module.exports: any;
}

declare module "imagemin-webpack-plugin/src/index" {
  declare module.exports: any;
}

// Filename aliases
declare module "imagemin-webpack-plugin/dist/helpers.js" {
  declare module.exports: $Exports<"imagemin-webpack-plugin/dist/helpers">;
}
declare module "imagemin-webpack-plugin/dist/index.js" {
  declare module.exports: $Exports<"imagemin-webpack-plugin/dist/index">;
}
declare module "imagemin-webpack-plugin/src/helpers.js" {
  declare module.exports: $Exports<"imagemin-webpack-plugin/src/helpers">;
}
declare module "imagemin-webpack-plugin/src/index.js" {
  declare module.exports: $Exports<"imagemin-webpack-plugin/src/index">;
}
