// flow-typed signature: 21627675ac98cb5c12eeccbf9a7f4c07
// flow-typed version: <<STUB>>/imagemin-webpack-plugin_v^1.4.4/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imagemin-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'imagemin-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'imagemin-webpack-plugin/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'imagemin-webpack-plugin/index.es5' {
  declare module.exports: any;
}

// Filename aliases
declare module 'imagemin-webpack-plugin/gulpfile.babel.js' {
  declare module.exports: $Exports<'imagemin-webpack-plugin/gulpfile.babel'>;
}
declare module 'imagemin-webpack-plugin/index.es5.js' {
  declare module.exports: $Exports<'imagemin-webpack-plugin/index.es5'>;
}
declare module 'imagemin-webpack-plugin/index' {
  declare module.exports: $Exports<'imagemin-webpack-plugin'>;
}
declare module 'imagemin-webpack-plugin/index.js' {
  declare module.exports: $Exports<'imagemin-webpack-plugin'>;
}
