// flow-typed signature: 7fa532b899130b33923c21bfda46318e
// flow-typed version: <<STUB>>/jest-puppeteer_v3.5.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-puppeteer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-puppeteer' {
  declare module.exports: any;
}
