// flow-typed signature: fa53e1ffc93f9aaed86a99532fea9905
// flow-typed version: <<STUB>>/jest-puppeteer_v3.8.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-puppeteer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-puppeteer' {
  declare module.exports: any;
}
