// flow-typed signature: 0ff5cd7f9af37c048abceb81f4296687
// flow-typed version: <<STUB>>/jest-puppeteer_v3.6.0/flow_v0.88.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-puppeteer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-puppeteer' {
  declare module.exports: any;
}
