// flow-typed signature: b323a33d12ec41ae5ce10eb84ccfdc1b
// flow-typed version: <<STUB>>/leaflet-plugins_v3.0.3/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaflet-plugins'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'leaflet-plugins' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'leaflet-plugins/control/Layers.Load' {
  declare module.exports: any;
}

declare module 'leaflet-plugins/control/Permalink' {
  declare module.exports: any;
}

declare module 'leaflet-plugins/control/Permalink.Layer' {
  declare module.exports: any;
}

declare module 'leaflet-plugins/control/Permalink.Line' {
  declare module.exports: any;
}

declare module 'leaflet-plugins/control/Permalink.Marker' {
  declare module.exports: any;
}

declare module 'leaflet-plugins/control/Permalink.Overlay' {
  declare module.exports: any;
}

declare module 'leaflet-plugins/control/test/PermalinkTest' {
  declare module.exports: any;
}

declare module 'leaflet-plugins/debug/leaflet-elevation/leaflet.elevation-0.0.4.min' {
  declare module.exports: any;
}

declare module 'leaflet-plugins/debug/leaflet-elevation/leaflet.elevation-0.0.4.src' {
  declare module.exports: any;
}

declare module 'leaflet-plugins/debug/leaflet-master/leaflet-src' {
  declare module.exports: any;
}

declare module 'leaflet-plugins/debug/leaflet-master/leaflet' {
  declare module.exports: any;
}

declare module 'leaflet-plugins/debug/leaflet-src' {
  declare module.exports: any;
}

declare module 'leaflet-plugins/layer/Icon.Canvas' {
  declare module.exports: any;
}

declare module 'leaflet-plugins/layer/Layer.Deferred' {
  declare module.exports: any;
}

declare module 'leaflet-plugins/layer/Marker.Rotate' {
  declare module.exports: any;
}

declare module 'leaflet-plugins/layer/Marker.Text' {
  declare module.exports: any;
}

declare module 'leaflet-plugins/layer/tile/Bing' {
  declare module.exports: any;
}

declare module 'leaflet-plugins/layer/tile/Yandex' {
  declare module.exports: any;
}

declare module 'leaflet-plugins/layer/vector/GPX' {
  declare module.exports: any;
}

declare module 'leaflet-plugins/layer/vector/GPX.Speed' {
  declare module.exports: any;
}

declare module 'leaflet-plugins/layer/vector/KML' {
  declare module.exports: any;
}

declare module 'leaflet-plugins/layer/vector/OSM' {
  declare module.exports: any;
}

declare module 'leaflet-plugins/layer/vector/TOPOJSON' {
  declare module.exports: any;
}

// Filename aliases
declare module 'leaflet-plugins/control/Layers.Load.js' {
  declare module.exports: $Exports<'leaflet-plugins/control/Layers.Load'>;
}
declare module 'leaflet-plugins/control/Permalink.js' {
  declare module.exports: $Exports<'leaflet-plugins/control/Permalink'>;
}
declare module 'leaflet-plugins/control/Permalink.Layer.js' {
  declare module.exports: $Exports<'leaflet-plugins/control/Permalink.Layer'>;
}
declare module 'leaflet-plugins/control/Permalink.Line.js' {
  declare module.exports: $Exports<'leaflet-plugins/control/Permalink.Line'>;
}
declare module 'leaflet-plugins/control/Permalink.Marker.js' {
  declare module.exports: $Exports<'leaflet-plugins/control/Permalink.Marker'>;
}
declare module 'leaflet-plugins/control/Permalink.Overlay.js' {
  declare module.exports: $Exports<'leaflet-plugins/control/Permalink.Overlay'>;
}
declare module 'leaflet-plugins/control/test/PermalinkTest.js' {
  declare module.exports: $Exports<'leaflet-plugins/control/test/PermalinkTest'>;
}
declare module 'leaflet-plugins/debug/leaflet-elevation/leaflet.elevation-0.0.4.min.js' {
  declare module.exports: $Exports<'leaflet-plugins/debug/leaflet-elevation/leaflet.elevation-0.0.4.min'>;
}
declare module 'leaflet-plugins/debug/leaflet-elevation/leaflet.elevation-0.0.4.src.js' {
  declare module.exports: $Exports<'leaflet-plugins/debug/leaflet-elevation/leaflet.elevation-0.0.4.src'>;
}
declare module 'leaflet-plugins/debug/leaflet-master/leaflet-src.js' {
  declare module.exports: $Exports<'leaflet-plugins/debug/leaflet-master/leaflet-src'>;
}
declare module 'leaflet-plugins/debug/leaflet-master/leaflet.js' {
  declare module.exports: $Exports<'leaflet-plugins/debug/leaflet-master/leaflet'>;
}
declare module 'leaflet-plugins/debug/leaflet-src.js' {
  declare module.exports: $Exports<'leaflet-plugins/debug/leaflet-src'>;
}
declare module 'leaflet-plugins/layer/Icon.Canvas.js' {
  declare module.exports: $Exports<'leaflet-plugins/layer/Icon.Canvas'>;
}
declare module 'leaflet-plugins/layer/Layer.Deferred.js' {
  declare module.exports: $Exports<'leaflet-plugins/layer/Layer.Deferred'>;
}
declare module 'leaflet-plugins/layer/Marker.Rotate.js' {
  declare module.exports: $Exports<'leaflet-plugins/layer/Marker.Rotate'>;
}
declare module 'leaflet-plugins/layer/Marker.Text.js' {
  declare module.exports: $Exports<'leaflet-plugins/layer/Marker.Text'>;
}
declare module 'leaflet-plugins/layer/tile/Bing.js' {
  declare module.exports: $Exports<'leaflet-plugins/layer/tile/Bing'>;
}
declare module 'leaflet-plugins/layer/tile/Yandex.js' {
  declare module.exports: $Exports<'leaflet-plugins/layer/tile/Yandex'>;
}
declare module 'leaflet-plugins/layer/vector/GPX.js' {
  declare module.exports: $Exports<'leaflet-plugins/layer/vector/GPX'>;
}
declare module 'leaflet-plugins/layer/vector/GPX.Speed.js' {
  declare module.exports: $Exports<'leaflet-plugins/layer/vector/GPX.Speed'>;
}
declare module 'leaflet-plugins/layer/vector/KML.js' {
  declare module.exports: $Exports<'leaflet-plugins/layer/vector/KML'>;
}
declare module 'leaflet-plugins/layer/vector/OSM.js' {
  declare module.exports: $Exports<'leaflet-plugins/layer/vector/OSM'>;
}
declare module 'leaflet-plugins/layer/vector/TOPOJSON.js' {
  declare module.exports: $Exports<'leaflet-plugins/layer/vector/TOPOJSON'>;
}
