// flow-typed signature: 4b806e7efb03db25de09a977f66198de
// flow-typed version: <<STUB>>/leaflet.browser.print_v0.7.0/flow_v0.88.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaflet.browser.print'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'leaflet.browser.print' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'leaflet.browser.print/dist/leaflet.browser.print' {
  declare module.exports: any;
}

declare module 'leaflet.browser.print/dist/leaflet.browser.print.min' {
  declare module.exports: any;
}

declare module 'leaflet.browser.print/examples/data/us-states' {
  declare module.exports: any;
}

declare module 'leaflet.browser.print/src/leaflet.browser.print' {
  declare module.exports: any;
}

declare module 'leaflet.browser.print/src/leaflet.browser.print.sizes' {
  declare module.exports: any;
}

declare module 'leaflet.browser.print/src/leaflet.browser.print.utils' {
  declare module.exports: any;
}

declare module 'leaflet.browser.print/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'leaflet.browser.print/dist/leaflet.browser.print.js' {
  declare module.exports: $Exports<'leaflet.browser.print/dist/leaflet.browser.print'>;
}
declare module 'leaflet.browser.print/dist/leaflet.browser.print.min.js' {
  declare module.exports: $Exports<'leaflet.browser.print/dist/leaflet.browser.print.min'>;
}
declare module 'leaflet.browser.print/examples/data/us-states.js' {
  declare module.exports: $Exports<'leaflet.browser.print/examples/data/us-states'>;
}
declare module 'leaflet.browser.print/src/leaflet.browser.print.js' {
  declare module.exports: $Exports<'leaflet.browser.print/src/leaflet.browser.print'>;
}
declare module 'leaflet.browser.print/src/leaflet.browser.print.sizes.js' {
  declare module.exports: $Exports<'leaflet.browser.print/src/leaflet.browser.print.sizes'>;
}
declare module 'leaflet.browser.print/src/leaflet.browser.print.utils.js' {
  declare module.exports: $Exports<'leaflet.browser.print/src/leaflet.browser.print.utils'>;
}
declare module 'leaflet.browser.print/webpack.config.js' {
  declare module.exports: $Exports<'leaflet.browser.print/webpack.config'>;
}
