/** @format */

// flow-typed signature: 48066bdc7fee21b0da9b009971032cfb
// flow-typed version: <<STUB>>/leaflet-modal_v0.2.0/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaflet-modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "leaflet-modal" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "leaflet-modal/dist/L.Modal" {
  declare module.exports: any;
}

declare module "leaflet-modal/dist/L.Modal.min" {
  declare module.exports: any;
}

declare module "leaflet-modal/examples/js/app" {
  declare module.exports: any;
}

declare module "leaflet-modal/examples/js/bundle" {
  declare module.exports: any;
}

declare module "leaflet-modal/examples/js/json-format" {
  declare module.exports: any;
}

declare module "leaflet-modal/rollup.config" {
  declare module.exports: any;
}

declare module "leaflet-modal/src/modal" {
  declare module.exports: any;
}

// Filename aliases
declare module "leaflet-modal/dist/L.Modal.js" {
  declare module.exports: $Exports<"leaflet-modal/dist/L.Modal">;
}
declare module "leaflet-modal/dist/L.Modal.min.js" {
  declare module.exports: $Exports<"leaflet-modal/dist/L.Modal.min">;
}
declare module "leaflet-modal/examples/js/app.js" {
  declare module.exports: $Exports<"leaflet-modal/examples/js/app">;
}
declare module "leaflet-modal/examples/js/bundle.js" {
  declare module.exports: $Exports<"leaflet-modal/examples/js/bundle">;
}
declare module "leaflet-modal/examples/js/json-format.js" {
  declare module.exports: $Exports<"leaflet-modal/examples/js/json-format">;
}
declare module "leaflet-modal/index" {
  declare module.exports: $Exports<"leaflet-modal">;
}
declare module "leaflet-modal/index.js" {
  declare module.exports: $Exports<"leaflet-modal">;
}
declare module "leaflet-modal/rollup.config.js" {
  declare module.exports: $Exports<"leaflet-modal/rollup.config">;
}
declare module "leaflet-modal/src/modal.js" {
  declare module.exports: $Exports<"leaflet-modal/src/modal">;
}
