// flow-typed signature: d70e7de1993c0f8cac502caa2ae6c558
// flow-typed version: <<STUB>>/leaflet-ajax_v2.1.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaflet-ajax'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'leaflet-ajax' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'leaflet-ajax/dist/leaflet.ajax' {
  declare module.exports: any;
}

declare module 'leaflet-ajax/dist/leaflet.ajax.min' {
  declare module.exports: any;
}

declare module 'leaflet-ajax/example/leaflet-src' {
  declare module.exports: any;
}

declare module 'leaflet-ajax/example/leaflet.spin' {
  declare module.exports: any;
}

declare module 'leaflet-ajax/example/spin' {
  declare module.exports: any;
}

declare module 'leaflet-ajax/server' {
  declare module.exports: any;
}

declare module 'leaflet-ajax/src/ajax' {
  declare module.exports: any;
}

declare module 'leaflet-ajax/src/index' {
  declare module.exports: any;
}

declare module 'leaflet-ajax/src/jsonp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'leaflet-ajax/dist/leaflet.ajax.js' {
  declare module.exports: $Exports<'leaflet-ajax/dist/leaflet.ajax'>;
}
declare module 'leaflet-ajax/dist/leaflet.ajax.min.js' {
  declare module.exports: $Exports<'leaflet-ajax/dist/leaflet.ajax.min'>;
}
declare module 'leaflet-ajax/example/leaflet-src.js' {
  declare module.exports: $Exports<'leaflet-ajax/example/leaflet-src'>;
}
declare module 'leaflet-ajax/example/leaflet.spin.js' {
  declare module.exports: $Exports<'leaflet-ajax/example/leaflet.spin'>;
}
declare module 'leaflet-ajax/example/spin.js' {
  declare module.exports: $Exports<'leaflet-ajax/example/spin'>;
}
declare module 'leaflet-ajax/server.js' {
  declare module.exports: $Exports<'leaflet-ajax/server'>;
}
declare module 'leaflet-ajax/src/ajax.js' {
  declare module.exports: $Exports<'leaflet-ajax/src/ajax'>;
}
declare module 'leaflet-ajax/src/index.js' {
  declare module.exports: $Exports<'leaflet-ajax/src/index'>;
}
declare module 'leaflet-ajax/src/jsonp.js' {
  declare module.exports: $Exports<'leaflet-ajax/src/jsonp'>;
}
