/** @format */

// flow-typed signature: f83fc2cad862eaa6f397b3086bf9fcab
// flow-typed version: <<STUB>>/leaflet.gridlayer.googlemutant_v^0.6.4/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaflet.gridlayer.googlemutant'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "leaflet.gridlayer.googlemutant" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "leaflet.gridlayer.googlemutant/Leaflet.GoogleMutant" {
  declare module.exports: any;
}

// Filename aliases
declare module "leaflet.gridlayer.googlemutant/Leaflet.GoogleMutant.js" {
  declare module.exports: $Exports<
    "leaflet.gridlayer.googlemutant/Leaflet.GoogleMutant"
  >;
}
