/** @format */

// flow-typed signature: e9162a13c273e72aff8fa87bec7f21a0
// flow-typed version: <<STUB>>/leaflet.browser.print_v^0.5.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaflet.browser.print'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "leaflet.browser.print" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "leaflet.browser.print/dist/leaflet.browser.print" {
  declare module.exports: any;
}

declare module "leaflet.browser.print/dist/leaflet.browser.print.min" {
  declare module.exports: any;
}

declare module "leaflet.browser.print/examples/data/us-states" {
  declare module.exports: any;
}

declare module "leaflet.browser.print/src/leaflet.browser.print" {
  declare module.exports: any;
}

declare module "leaflet.browser.print/src/leaflet.browser.print.utils" {
  declare module.exports: any;
}

declare module "leaflet.browser.print/webpack.config" {
  declare module.exports: any;
}

// Filename aliases
declare module "leaflet.browser.print/dist/leaflet.browser.print.js" {
  declare module.exports: $Exports<
    "leaflet.browser.print/dist/leaflet.browser.print"
  >;
}
declare module "leaflet.browser.print/dist/leaflet.browser.print.min.js" {
  declare module.exports: $Exports<
    "leaflet.browser.print/dist/leaflet.browser.print.min"
  >;
}
declare module "leaflet.browser.print/examples/data/us-states.js" {
  declare module.exports: $Exports<
    "leaflet.browser.print/examples/data/us-states"
  >;
}
declare module "leaflet.browser.print/src/leaflet.browser.print.js" {
  declare module.exports: $Exports<
    "leaflet.browser.print/src/leaflet.browser.print"
  >;
}
declare module "leaflet.browser.print/src/leaflet.browser.print.utils.js" {
  declare module.exports: $Exports<
    "leaflet.browser.print/src/leaflet.browser.print.utils"
  >;
}
declare module "leaflet.browser.print/webpack.config.js" {
  declare module.exports: $Exports<"leaflet.browser.print/webpack.config">;
}
