/** @format */

// flow-typed signature: ac0d624872f49a700b647e1fd6835a4f
// flow-typed version: <<STUB>>/leaflet-dialog_v1.0.4/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaflet-dialog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "leaflet-dialog" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "leaflet-dialog/Leaflet.Dialog" {
  declare module.exports: any;
}

// Filename aliases
declare module "leaflet-dialog/Leaflet.Dialog.js" {
  declare module.exports: $Exports<"leaflet-dialog/Leaflet.Dialog">;
}
