/** @format */

// flow-typed signature: ed07e4d6e54e5810ce29fb929b22b2c0
// flow-typed version: <<STUB>>/leaflet-hash_v^0.2.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaflet-hash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "leaflet-hash" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "leaflet-hash/leaflet-hash" {
  declare module.exports: any;
}

declare module "leaflet-hash/lib/leaflet-src" {
  declare module.exports: any;
}

declare module "leaflet-hash/test/spec/hash" {
  declare module.exports: any;
}

// Filename aliases
declare module "leaflet-hash/leaflet-hash.js" {
  declare module.exports: $Exports<"leaflet-hash/leaflet-hash">;
}
declare module "leaflet-hash/lib/leaflet-src.js" {
  declare module.exports: $Exports<"leaflet-hash/lib/leaflet-src">;
}
declare module "leaflet-hash/test/spec/hash.js" {
  declare module.exports: $Exports<"leaflet-hash/test/spec/hash">;
}
