/** @format */

// flow-typed signature: 06c999053842618065a71917a06035ee
// flow-typed version: <<STUB>>/leaflet.photon_v0.8.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaflet.photon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "leaflet.photon" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "leaflet.photon/leaflet.photon" {
  declare module.exports: any;
}

// Filename aliases
declare module "leaflet.photon/leaflet.photon.js" {
  declare module.exports: $Exports<"leaflet.photon/leaflet.photon">;
}
