// flow-typed signature: bfaacd2804a0f56fba009b56f681bf36
// flow-typed version: <<STUB>>/load-google-maps-api_v^1.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'load-google-maps-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'load-google-maps-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'load-google-maps-api/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'load-google-maps-api/index' {
  declare module.exports: $Exports<'load-google-maps-api'>;
}
declare module 'load-google-maps-api/index.js' {
  declare module.exports: $Exports<'load-google-maps-api'>;
}
declare module 'load-google-maps-api/test.js' {
  declare module.exports: $Exports<'load-google-maps-api/test'>;
}
