/** @format */

// flow-typed signature: 6cb5b1d2651e7dfb5d455eb44d4abffb
// flow-typed version: <<STUB>>/material-design-iconic-font_v^2.2.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-design-iconic-font'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "material-design-iconic-font" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "material-design-iconic-font/grunt/clean" {
  declare module.exports: any;
}

declare module "material-design-iconic-font/grunt/concurrent" {
  declare module.exports: any;
}

declare module "material-design-iconic-font/grunt/copy" {
  declare module.exports: any;
}

declare module "material-design-iconic-font/grunt/less" {
  declare module.exports: any;
}

declare module "material-design-iconic-font/grunt/lessToSass" {
  declare module.exports: any;
}

declare module "material-design-iconic-font/grunt/pleeease" {
  declare module.exports: any;
}

declare module "material-design-iconic-font/grunt/replace" {
  declare module.exports: any;
}

declare module "material-design-iconic-font/grunt/svgmin" {
  declare module.exports: any;
}

declare module "material-design-iconic-font/grunt/webfont" {
  declare module.exports: any;
}

declare module "material-design-iconic-font/Gruntfile" {
  declare module.exports: any;
}

// Filename aliases
declare module "material-design-iconic-font/grunt/clean.js" {
  declare module.exports: $Exports<"material-design-iconic-font/grunt/clean">;
}
declare module "material-design-iconic-font/grunt/concurrent.js" {
  declare module.exports: $Exports<
    "material-design-iconic-font/grunt/concurrent"
  >;
}
declare module "material-design-iconic-font/grunt/copy.js" {
  declare module.exports: $Exports<"material-design-iconic-font/grunt/copy">;
}
declare module "material-design-iconic-font/grunt/less.js" {
  declare module.exports: $Exports<"material-design-iconic-font/grunt/less">;
}
declare module "material-design-iconic-font/grunt/lessToSass.js" {
  declare module.exports: $Exports<
    "material-design-iconic-font/grunt/lessToSass"
  >;
}
declare module "material-design-iconic-font/grunt/pleeease.js" {
  declare module.exports: $Exports<
    "material-design-iconic-font/grunt/pleeease"
  >;
}
declare module "material-design-iconic-font/grunt/replace.js" {
  declare module.exports: $Exports<"material-design-iconic-font/grunt/replace">;
}
declare module "material-design-iconic-font/grunt/svgmin.js" {
  declare module.exports: $Exports<"material-design-iconic-font/grunt/svgmin">;
}
declare module "material-design-iconic-font/grunt/webfont.js" {
  declare module.exports: $Exports<"material-design-iconic-font/grunt/webfont">;
}
declare module "material-design-iconic-font/Gruntfile.js" {
  declare module.exports: $Exports<"material-design-iconic-font/Gruntfile">;
}
