/** @format */

// flow-typed signature: 7226aadcf7b3ee438cc07964d35c7a34
// flow-typed version: <<STUB>>/opensans-npm-webfont_v^1.0.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'opensans-npm-webfont'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "opensans-npm-webfont" {
  declare module.exports: any;
}
