// flow-typed signature: 762053c65a5f792876abdefd646d14bd
// flow-typed version: <<STUB>>/opensans-npm-webfont_v1.0.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'opensans-npm-webfont'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'opensans-npm-webfont' {
  declare module.exports: any;
}
