/** @format */

// flow-typed signature: ceb5f1f0c6e8115d15da2e70dac4b13e
// flow-typed version: <<STUB>>/opensans-npm-webfont_v1.0.0/flow_v0.103.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'opensans-npm-webfont'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "opensans-npm-webfont" {
  declare module.exports: any;
}
