// flow-typed signature: d738e5f2a973572233a255fa5bb4047a
// flow-typed version: <<STUB>>/postcss-preset-env_v6.4.0/flow_v0.88.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-preset-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-preset-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-preset-env/index.cjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-preset-env/index.cjs.js' {
  declare module.exports: $Exports<'postcss-preset-env/index.cjs'>;
}
