/** @format */

// flow-typed signature: e04956f23c2838549e7d171d1ccd4d2b
// flow-typed version: <<STUB>>/postcss-preset-env_v6.0.7/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-preset-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "postcss-preset-env" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "postcss-preset-env/index.cjs" {
  declare module.exports: any;
}

// Filename aliases
declare module "postcss-preset-env/index.cjs.js" {
  declare module.exports: $Exports<"postcss-preset-env/index.cjs">;
}
