/** @format */

// flow-typed signature: d3c4a46b87949f3e136a5e15605ef6fb
// flow-typed version: <<STUB>>/tapable_v^1.0.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tapable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "tapable" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "tapable/lib/__tests__/AsyncParallelHooks" {
  declare module.exports: any;
}

declare module "tapable/lib/__tests__/AsyncSeriesHooks" {
  declare module.exports: any;
}

declare module "tapable/lib/__tests__/Hook" {
  declare module.exports: any;
}

declare module "tapable/lib/__tests__/HookCodeFactory" {
  declare module.exports: any;
}

declare module "tapable/lib/__tests__/HookTester" {
  declare module.exports: any;
}

declare module "tapable/lib/__tests__/MultiHook" {
  declare module.exports: any;
}

declare module "tapable/lib/__tests__/SyncBailHook" {
  declare module.exports: any;
}

declare module "tapable/lib/__tests__/SyncHook" {
  declare module.exports: any;
}

declare module "tapable/lib/__tests__/SyncHooks" {
  declare module.exports: any;
}

declare module "tapable/lib/__tests__/Tapable" {
  declare module.exports: any;
}

declare module "tapable/lib/AsyncParallelBailHook" {
  declare module.exports: any;
}

declare module "tapable/lib/AsyncParallelHook" {
  declare module.exports: any;
}

declare module "tapable/lib/AsyncSeriesBailHook" {
  declare module.exports: any;
}

declare module "tapable/lib/AsyncSeriesHook" {
  declare module.exports: any;
}

declare module "tapable/lib/AsyncSeriesLoopHook" {
  declare module.exports: any;
}

declare module "tapable/lib/AsyncSeriesWaterfallHook" {
  declare module.exports: any;
}

declare module "tapable/lib/Hook" {
  declare module.exports: any;
}

declare module "tapable/lib/HookCodeFactory" {
  declare module.exports: any;
}

declare module "tapable/lib/HookMap" {
  declare module.exports: any;
}

declare module "tapable/lib/index" {
  declare module.exports: any;
}

declare module "tapable/lib/MultiHook" {
  declare module.exports: any;
}

declare module "tapable/lib/simpleAsyncCases" {
  declare module.exports: any;
}

declare module "tapable/lib/SyncBailHook" {
  declare module.exports: any;
}

declare module "tapable/lib/SyncHook" {
  declare module.exports: any;
}

declare module "tapable/lib/SyncLoopHook" {
  declare module.exports: any;
}

declare module "tapable/lib/SyncWaterfallHook" {
  declare module.exports: any;
}

declare module "tapable/lib/Tapable" {
  declare module.exports: any;
}

// Filename aliases
declare module "tapable/lib/__tests__/AsyncParallelHooks.js" {
  declare module.exports: $Exports<"tapable/lib/__tests__/AsyncParallelHooks">;
}
declare module "tapable/lib/__tests__/AsyncSeriesHooks.js" {
  declare module.exports: $Exports<"tapable/lib/__tests__/AsyncSeriesHooks">;
}
declare module "tapable/lib/__tests__/Hook.js" {
  declare module.exports: $Exports<"tapable/lib/__tests__/Hook">;
}
declare module "tapable/lib/__tests__/HookCodeFactory.js" {
  declare module.exports: $Exports<"tapable/lib/__tests__/HookCodeFactory">;
}
declare module "tapable/lib/__tests__/HookTester.js" {
  declare module.exports: $Exports<"tapable/lib/__tests__/HookTester">;
}
declare module "tapable/lib/__tests__/MultiHook.js" {
  declare module.exports: $Exports<"tapable/lib/__tests__/MultiHook">;
}
declare module "tapable/lib/__tests__/SyncBailHook.js" {
  declare module.exports: $Exports<"tapable/lib/__tests__/SyncBailHook">;
}
declare module "tapable/lib/__tests__/SyncHook.js" {
  declare module.exports: $Exports<"tapable/lib/__tests__/SyncHook">;
}
declare module "tapable/lib/__tests__/SyncHooks.js" {
  declare module.exports: $Exports<"tapable/lib/__tests__/SyncHooks">;
}
declare module "tapable/lib/__tests__/Tapable.js" {
  declare module.exports: $Exports<"tapable/lib/__tests__/Tapable">;
}
declare module "tapable/lib/AsyncParallelBailHook.js" {
  declare module.exports: $Exports<"tapable/lib/AsyncParallelBailHook">;
}
declare module "tapable/lib/AsyncParallelHook.js" {
  declare module.exports: $Exports<"tapable/lib/AsyncParallelHook">;
}
declare module "tapable/lib/AsyncSeriesBailHook.js" {
  declare module.exports: $Exports<"tapable/lib/AsyncSeriesBailHook">;
}
declare module "tapable/lib/AsyncSeriesHook.js" {
  declare module.exports: $Exports<"tapable/lib/AsyncSeriesHook">;
}
declare module "tapable/lib/AsyncSeriesLoopHook.js" {
  declare module.exports: $Exports<"tapable/lib/AsyncSeriesLoopHook">;
}
declare module "tapable/lib/AsyncSeriesWaterfallHook.js" {
  declare module.exports: $Exports<"tapable/lib/AsyncSeriesWaterfallHook">;
}
declare module "tapable/lib/Hook.js" {
  declare module.exports: $Exports<"tapable/lib/Hook">;
}
declare module "tapable/lib/HookCodeFactory.js" {
  declare module.exports: $Exports<"tapable/lib/HookCodeFactory">;
}
declare module "tapable/lib/HookMap.js" {
  declare module.exports: $Exports<"tapable/lib/HookMap">;
}
declare module "tapable/lib/index.js" {
  declare module.exports: $Exports<"tapable/lib/index">;
}
declare module "tapable/lib/MultiHook.js" {
  declare module.exports: $Exports<"tapable/lib/MultiHook">;
}
declare module "tapable/lib/simpleAsyncCases.js" {
  declare module.exports: $Exports<"tapable/lib/simpleAsyncCases">;
}
declare module "tapable/lib/SyncBailHook.js" {
  declare module.exports: $Exports<"tapable/lib/SyncBailHook">;
}
declare module "tapable/lib/SyncHook.js" {
  declare module.exports: $Exports<"tapable/lib/SyncHook">;
}
declare module "tapable/lib/SyncLoopHook.js" {
  declare module.exports: $Exports<"tapable/lib/SyncLoopHook">;
}
declare module "tapable/lib/SyncWaterfallHook.js" {
  declare module.exports: $Exports<"tapable/lib/SyncWaterfallHook">;
}
declare module "tapable/lib/Tapable.js" {
  declare module.exports: $Exports<"tapable/lib/Tapable">;
}
