// flow-typed signature: c56ebb89992570906434a5a8514ef28a
// flow-typed version: <<STUB>>/ua-parser-js_v^0.7.12/flow_v0.49.1

/* eslint-disable flowtype/no-types-missing-file-annotation */

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ua-parser-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */
//declare class _BrowserName: "Amaya"| "Android Browser"| "Arora"| "Avant"| "Baidu"| "Blazer"| Bolt, Bowser, Camino, Chimera, Chrome [WebView], Chromium, Comodo Dragon, Conkeror, Dillo, Dolphin, Doris, Edge, Epiphany, Fennec, Firebird, Firefox, Flock, GoBrowser, iCab, ICE Browser, IceApe, IceCat, IceDragon, Iceweasel, IE[Mobile], Iron, Jasmine, K-Meleon, Konqueror, Kindle, Links, Lunascape, Lynx, Maemo, Maxthon, Midori, Minimo, MIUI Browser, [Mobile] Safari, Mosaic, Mozilla, Netfront, Netscape, NetSurf, Nokia, OmniWeb, Opera [Mini/Mobi/Tablet], PhantomJS, Phoenix, Polaris, QQBrowser, RockMelt, Silk, Skyfire, SeaMonkey, Sleipnir, SlimBrowser, Swiftfox, Tizen, UCBrowser, Vivaldi, w3m, WeChat, Yandex;

declare class Browser { name: string, version: string };

declare type DeviceType= 
  | "console" 
  | "mobile" 
  | "tablet" 
  | "smarttv" 
  | "wearable" 
  | "embedded";

declare class Device { model: string, type: DeviceType, vendor: string };

declare class Engine { name: string, version: string };

declare class OS { name: string, version: string };

declare class CPU { architecture: string };

declare class ua {
  ua: string;
  browser: Browser;
  cpu: CPU;
  device: Device;
  engine: Engine;
  os: OS;
}

declare class UAParser extends ua{
  
  getBrowser(): Browser;
  getDevice(): Device;
  getEngine(): Engine;
  getOS(): OS;
  getCPU(): CPU;
  getResult(): ua;


}
declare module 'ua-parser-js' {
  declare module.exports: uaParser;
  
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ua-parser-js/dist/ua-parser.min' {
  declare module.exports: any;
}

declare module 'ua-parser-js/dist/ua-parser.pack' {
  declare module.exports: any;
}

declare module 'ua-parser-js/package' {
  declare module.exports: any;
}

declare module 'ua-parser-js/src/ua-parser' {
  declare module.exports: any;
}

declare module 'ua-parser-js/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ua-parser-js/dist/ua-parser.min.js' {
  declare module.exports: $Exports<'ua-parser-js/dist/ua-parser.min'>;
}
declare module 'ua-parser-js/dist/ua-parser.pack.js' {
  declare module.exports: $Exports<'ua-parser-js/dist/ua-parser.pack'>;
}
declare module 'ua-parser-js/package.js' {
  declare module.exports: $Exports<'ua-parser-js/package'>;
}
declare module 'ua-parser-js/src/ua-parser.js' {
  declare module.exports: $Exports<'ua-parser-js/src/ua-parser'>;
}
declare module 'ua-parser-js/test/test.js' {
  declare module.exports: $Exports<'ua-parser-js/test/test'>;
}
