/** @format */

// flow-typed signature: f28caee0b46e33c917526b1fdba0b7c0
// flow-typed version: <<STUB>>/@babel/preset-stage-0_v7.8.3/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/preset-stage-0'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@babel/preset-stage-0" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@babel/preset-stage-0/lib" {
  declare module.exports: any;
}

// Filename aliases
declare module "@babel/preset-stage-0/lib/index" {
  declare module.exports: $Exports<"@babel/preset-stage-0/lib">;
}
declare module "@babel/preset-stage-0/lib/index.js" {
  declare module.exports: $Exports<"@babel/preset-stage-0/lib">;
}
