/** @format */

// flow-typed signature: 3374aaa23bf47b95751439805c3823de
// flow-typed version: <<STUB>>/@babel/preset-stage-0_v^7.0.0-beta.49/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/preset-stage-0'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@babel/preset-stage-0" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@babel/preset-stage-0/lib/index" {
  declare module.exports: any;
}

// Filename aliases
declare module "@babel/preset-stage-0/lib/index.js" {
  declare module.exports: $Exports<"@babel/preset-stage-0/lib/index">;
}
